/* No possibility to fetch different dishTypes from API for filtering
Edamam recepies API docs only provide the different categories to fetch data */

export const meals = {
  diet: [
    'balanced',
    'high-fiber',
    'high-protein',
    'low-carb',
    'low-fat',
    'low-sodium',
  ],
  health: [
    'alcohol-cocktail',
    'alcohol-free',
    'celery-free',
    'crustacean-free',
    'dairy-free',
    'DASH',
    'egg-free',
    'fish-free',
    'foodmap-free',
    'gluten-free',
    'immuno-supportive',
    'keto-friendly',
    'kidney-friendly',
    'kosher',
    'low-fat-abs',
    'low-potassium',
    'low-sugar',
    'lupine-free',
    'Medditerranean',
    'mollusk-free',
    'mustard-free',
    'no-oil-added',
    'paleo',
    'peanut-free',
    'pescatarian',
    'pork-free',
    'red-meat-free',
    'sesame-free',
    'shellfish-free',
    'soy-free',
    'sugar-conscious',
    'sulfite-free',
    'tree-nut-free',
    'vegan',
    'vegeterian',
    'wheat-free',
  ],
  mealType: ['Breakfast', 'Dinner', 'Lunch', 'Snack', 'Teatime'],
  dishType: [
    'Biscuits and Cookies',
    'Bread',
    'Cereals',
    'Condiments and Sauces',
    'Desserts',
    'Drinks',
    'Egg',
    'Ice cream and custard',
    'Main course',
    'Pancake',
    'Pasta',
    'Pastry',
    'Pies and tarts',
    'Pizza',
    'Preps',
    'Preserve',
    'Salad',
    'Sandwiches',
    'Seafood',
    'Side dish',
    'Soup',
    'Special occasions',
    'Starter',
    'Sweets',
  ],
  cuisineType: [
    'American',
    'Asian',
    'British',
    'Caribbean',
    'Central Europe',
    'Chinese',
    'Eastern europe',
    'French',
    'Greek',
    'Indian',
    'Italian',
    'Japanese',
    'Korean',
    'Kosher',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'South American',
    'South East Asian',
    'World',
  ],
};
